name: CD

on:
    push:
        tags:
            - "v*"

    workflow_dispatch:

permissions:
    contents: write

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgres://bofe:bofe@127.0.0.1:5432/bofe_dev

jobs:
    build_api:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: bofe
                    POSTGRES_PASSWORD: bofe
                    POSTGRES_DB: bofe_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/setup-rust
            - run: cargo build --package bofe-api --release
            - uses: actions/upload-artifact@v7
              with:
                  name: bofe_api_build
                  path: ./target/release/bofe-api
                  retention-days: 1
                  overwrite: true

    build_cli:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: bofe
                    POSTGRES_PASSWORD: bofe
                    POSTGRES_DB: bofe_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/setup-rust
            - run: cargo build --package bofe-cli --release
            - uses: actions/upload-artifact@v7
              with:
                  name: bofe_cli_build
                  path: ./target/release/bofe-cli
                  retention-days: 1
                  overwrite: true

    build_monitor:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:17-alpine
                env:
                    POSTGRES_USER: bofe
                    POSTGRES_PASSWORD: bofe
                    POSTGRES_DB: bofe_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v7
            - uses: ./.github/actions/setup-rust
            - run: cargo build --package bofe-monitor --release
            - uses: actions/upload-artifact@v7
              with:
                  name: bofe_monitor_build
                  path: ./target/release/bofe-monitor
                  retention-days: 1
                  overwrite: true

    dump_graphql_schema:
        needs: [build_cli]
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: bofe
                    POSTGRES_PASSWORD: bofe
                    POSTGRES_DB: bofe_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
        steps:
            - uses: actions/checkout@v7
            - uses: actions/download-artifact@v8
              with:
                  name: bofe_cli_build
                  path: artifact/
            - run: |
                  chmod +x ./artifact/bofe-cli
                  ./artifact/bofe-cli graphql-schema | tee ./bofe-${{ github.ref_name }}.graphql
            - uses: actions/upload-artifact@v7
              with:
                  name: bofe_graphql_schema
                  path: ./bofe-${{ github.ref_name }}.graphql
                  retention-days: 1
                  overwrite: true

    release:
        needs: [dump_graphql_schema]
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v7
            - uses: actions/download-artifact@v8
              with:
                  name: bofe_graphql_schema
                  path: artifact/
            - uses: softprops/action-gh-release@v3
              with:
                  files: artifact/bofe-${{ github.ref_name }}.graphql
                  generate_release_notes: true
                  prerelease: ${{ contains(github.ref_name, '-alpha') }}

    deploy:
        environment:
            name: production
            url: https://api.bofe.app/
        needs: [build_api, build_cli, build_monitor]
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v7
            - uses: actions/download-artifact@v8
              with:
                  name: bofe_api_build
                  path: artifact/
            - uses: actions/download-artifact@v8
              with:
                  name: bofe_cli_build
                  path: artifact/
            - uses: actions/download-artifact@v8
              with:
                  name: bofe_monitor_build
                  path: artifact/
            - name: Run deploy script
              run: ${{ secrets.DEPLOY_SCRIPT }}
