name: Tests

on:
    workflow_call:

env:
    CARGO_TERM_COLOR: always
    DATABASE_URL: postgres://bofe:bofe@127.0.0.1:5432/bofe_dev

jobs:
    unit_tests:
        runs-on: ubuntu-24.04
        services:
            postgres:
                image: postgres:18-alpine
                env:
                    POSTGRES_USER: bofe
                    POSTGRES_PASSWORD: bofe
                    POSTGRES_DB: bofe_dev
                ports:
                    - 5432:5432
                options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
            redis:
                image: redis:8-alpine
                options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5
                ports:
                    - 6379:6379

        steps:
            - uses: actions/checkout@v7
            - uses: taiki-e/install-action@nextest
            - uses: ./.github/actions/setup-rust
            - name: Run all unit tests
              run: cargo nextest run --no-tests pass
